'use strict';
/* ============================================================
 * 数据仓库 data.js
 * 数据源：Corpus/FLE（新经典法语Clean1/2）+ 用户课表/学生名单
 * 未来可直接编辑本文件，或通过《教学大纲与知识点-整理清单.md》重新生成
 * ============================================================ */
const timetable = [
  {"id": "t1", "week": 2, "day": "周二", "period": 1, "displayName": "第2周周二(9.15) 第1大节", "room": "叶耀珍楼407", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t2", "week": 2, "day": "周二", "period": 2, "displayName": "第2周周二(9.15) 第2大节", "room": "叶耀珍楼407", "periods": "5-6节", "cancelled": false, "originalNote": ""},
  {"id": "t3", "week": 2, "day": "周三", "period": 1, "displayName": "第2周周三(9.16) 第1大节", "room": "叶耀珍楼304", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t4", "week": 2, "day": "周三", "period": 2, "displayName": "第2周周三(9.16) 第2大节", "room": "叶耀珍楼304", "periods": "5-6节", "cancelled": false, "originalNote": ""},
  {"id": "t5", "week": 2, "day": "周四", "period": 1, "displayName": "第2周周四(9.17) 第1大节", "room": "叶耀珍楼407", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t6", "week": 2, "day": "周四", "period": 2, "displayName": "第2周周四(9.17) 第2大节", "room": "叶耀珍楼407", "periods": "5-6节", "cancelled": false, "originalNote": ""},
  {"id": "t7", "week": 2, "day": "周五", "period": 1, "displayName": "第2周周五(9.18) 第1大节", "room": "叶耀珍楼407", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t8", "week": 2, "day": "周日", "period": 1, "displayName": "第2周周日(9.20) 第1大节", "room": "叶耀珍楼407", "periods": "3-4节", "cancelled": false, "originalNote": "原课程：第3周周五9.25"},
  {"id": "t9", "week": 3, "day": "周二", "period": 1, "displayName": "第3周周二(9.22) 第1大节", "room": "叶耀珍楼407", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t10", "week": 3, "day": "周二", "period": 2, "displayName": "第3周周二(9.22) 第2大节", "room": "叶耀珍楼407", "periods": "5-6节", "cancelled": false, "originalNote": ""},
  {"id": "t11", "week": 3, "day": "周三", "period": 1, "displayName": "第3周周三(9.23) 第1大节", "room": "叶耀珍楼304", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t12", "week": 3, "day": "周三", "period": 2, "displayName": "第3周周三(9.23) 第2大节", "room": "叶耀珍楼304", "periods": "5-6节", "cancelled": false, "originalNote": ""},
  {"id": "t13", "week": 3, "day": "周四", "period": 1, "displayName": "第3周周四(9.24) 第1大节", "room": "叶耀珍楼407", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t14", "week": 3, "day": "周四", "period": 2, "displayName": "第3周周四(9.24) 第2大节", "room": "叶耀珍楼407", "periods": "5-6节", "cancelled": false, "originalNote": ""},
  {"id": "t15", "week": 4, "day": "周二", "period": 1, "displayName": "第4周周二(9.29) 第1大节", "room": "叶耀珍楼407", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t16", "week": 4, "day": "周二", "period": 2, "displayName": "第4周周二(9.29) 第2大节", "room": "叶耀珍楼407", "periods": "5-6节", "cancelled": false, "originalNote": ""},
  {"id": "t17", "week": 4, "day": "周三", "period": 1, "displayName": "第4周周三(9.30) 第1大节", "room": "叶耀珍楼304", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t18", "week": 4, "day": "周三", "period": 2, "displayName": "第4周周三(9.30) 第2大节", "room": "叶耀珍楼304", "periods": "5-6节", "cancelled": false, "originalNote": ""},
  {"id": "t19", "week": 4, "day": "周四", "period": 1, "displayName": "第4周周四(10.1) 第1大节", "room": "叶耀珍楼407", "periods": "3-4节", "cancelled": true, "originalNote": ""},
  {"id": "t20", "week": 4, "day": "周四", "period": 2, "displayName": "第4周周四(10.1) 第2大节", "room": "叶耀珍楼407", "periods": "5-6节", "cancelled": true, "originalNote": ""},
  {"id": "t21", "week": 5, "day": "周二", "period": 1, "displayName": "第5周周二(10.6) 第1大节", "room": "叶耀珍楼407", "periods": "3-4节", "cancelled": true, "originalNote": ""},
  {"id": "t22", "week": 5, "day": "周二", "period": 2, "displayName": "第5周周二(10.6) 第2大节", "room": "叶耀珍楼407", "periods": "5-6节", "cancelled": true, "originalNote": ""},
  {"id": "t23", "week": 5, "day": "周三", "period": 1, "displayName": "第5周周三(10.7) 第1大节", "room": "叶耀珍楼304", "periods": "3-4节", "cancelled": true, "originalNote": ""},
  {"id": "t24", "week": 5, "day": "周三", "period": 2, "displayName": "第5周周三(10.7) 第2大节", "room": "叶耀珍楼304", "periods": "5-6节", "cancelled": true, "originalNote": ""},
  {"id": "t25", "week": 5, "day": "周四", "period": 1, "displayName": "第5周周四(10.8) 第1大节", "room": "叶耀珍楼407", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t26", "week": 5, "day": "周四", "period": 2, "displayName": "第5周周四(10.8) 第2大节", "room": "叶耀珍楼407", "periods": "5-6节", "cancelled": false, "originalNote": ""},
  {"id": "t27", "week": 5, "day": "周五", "period": 1, "displayName": "第5周周五(10.9) 第1大节", "room": "叶耀珍楼407", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t28", "week": 5, "day": "周六", "period": 1, "displayName": "第5周周六(10.10) 第1大节", "room": "叶耀珍楼407", "periods": "3-4节", "cancelled": false, "originalNote": "原课程：第4周周五10.2"},
  {"id": "t29", "week": 6, "day": "周二", "period": 1, "displayName": "第6周周二(10.13) 第1大节", "room": "叶耀珍楼407", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t30", "week": 6, "day": "周二", "period": 2, "displayName": "第6周周二(10.13) 第2大节", "room": "叶耀珍楼407", "periods": "5-6节", "cancelled": false, "originalNote": ""},
  {"id": "t31", "week": 6, "day": "周三", "period": 1, "displayName": "第6周周三(10.14) 第1大节", "room": "叶耀珍楼304", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t32", "week": 6, "day": "周三", "period": 2, "displayName": "第6周周三(10.14) 第2大节", "room": "叶耀珍楼304", "periods": "5-6节", "cancelled": false, "originalNote": ""},
  {"id": "t33", "week": 6, "day": "周四", "period": 1, "displayName": "第6周周四(10.15) 第1大节", "room": "叶耀珍楼407", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t34", "week": 6, "day": "周四", "period": 2, "displayName": "第6周周四(10.15) 第2大节", "room": "叶耀珍楼407", "periods": "5-6节", "cancelled": false, "originalNote": ""},
  {"id": "t35", "week": 6, "day": "周五", "period": 1, "displayName": "第6周周五(10.16) 第1大节", "room": "叶耀珍楼407", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t36", "week": 7, "day": "周二", "period": 1, "displayName": "第7周周二(10.20) 第1大节", "room": "叶耀珍楼407", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t37", "week": 7, "day": "周二", "period": 2, "displayName": "第7周周二(10.20) 第2大节", "room": "叶耀珍楼407", "periods": "5-6节", "cancelled": false, "originalNote": ""},
  {"id": "t38", "week": 7, "day": "周三", "period": 1, "displayName": "第7周周三(10.21) 第1大节", "room": "叶耀珍楼304", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t39", "week": 7, "day": "周三", "period": 2, "displayName": "第7周周三(10.21) 第2大节", "room": "叶耀珍楼304", "periods": "5-6节", "cancelled": false, "originalNote": ""},
  {"id": "t40", "week": 7, "day": "周四", "period": 1, "displayName": "第7周周四(10.22) 第1大节", "room": "叶耀珍楼407", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t41", "week": 7, "day": "周四", "period": 2, "displayName": "第7周周四(10.22) 第2大节", "room": "叶耀珍楼407", "periods": "5-6节", "cancelled": false, "originalNote": ""},
  {"id": "t42", "week": 7, "day": "周五", "period": 1, "displayName": "第7周周五(10.23) 第1大节", "room": "叶耀珍楼407", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t43", "week": 8, "day": "周二", "period": 1, "displayName": "第8周周二(10.27) 第1大节", "room": "叶耀珍楼407", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t44", "week": 8, "day": "周二", "period": 2, "displayName": "第8周周二(10.27) 第2大节", "room": "叶耀珍楼407", "periods": "5-6节", "cancelled": false, "originalNote": ""},
  {"id": "t45", "week": 8, "day": "周三", "period": 1, "displayName": "第8周周三(10.28) 第1大节", "room": "叶耀珍楼304", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t46", "week": 8, "day": "周三", "period": 2, "displayName": "第8周周三(10.28) 第2大节", "room": "叶耀珍楼304", "periods": "5-6节", "cancelled": false, "originalNote": ""},
  {"id": "t47", "week": 8, "day": "周四", "period": 1, "displayName": "第8周周四(10.29) 第1大节", "room": "叶耀珍楼407", "periods": "3-4节", "cancelled": true, "originalNote": ""},
  {"id": "t48", "week": 8, "day": "周四", "period": 2, "displayName": "第8周周四(10.29) 第2大节", "room": "叶耀珍楼407", "periods": "5-6节", "cancelled": true, "originalNote": ""},
  {"id": "t49", "week": 8, "day": "周五", "period": 1, "displayName": "第8周周五(10.30) 第1大节", "room": "叶耀珍楼407", "periods": "3-4节", "cancelled": true, "originalNote": ""},
  {"id": "t50", "week": 9, "day": "周二", "period": 1, "displayName": "第9周周二(11.3) 第1大节", "room": "叶耀珍楼407", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t51", "week": 9, "day": "周二", "period": 2, "displayName": "第9周周二(11.3) 第2大节", "room": "叶耀珍楼407", "periods": "5-6节", "cancelled": false, "originalNote": ""},
  {"id": "t52", "week": 9, "day": "周三", "period": 1, "displayName": "第9周周三(11.4) 第1大节", "room": "叶耀珍楼304", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t53", "week": 9, "day": "周三", "period": 2, "displayName": "第9周周三(11.4) 第2大节", "room": "叶耀珍楼304", "periods": "5-6节", "cancelled": false, "originalNote": ""},
  {"id": "t54", "week": 9, "day": "周四", "period": 1, "displayName": "第9周周四(11.5) 第1大节", "room": "叶耀珍楼407", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t55", "week": 9, "day": "周四", "period": 2, "displayName": "第9周周四(11.5) 第2大节", "room": "叶耀珍楼407", "periods": "5-6节", "cancelled": false, "originalNote": ""},
  {"id": "t56", "week": 9, "day": "周五", "period": 1, "displayName": "第9周周五(11.6) 第1大节", "room": "叶耀珍楼407", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t57", "week": 10, "day": "周二", "period": 1, "displayName": "第10周周二(11.10) 第1大节", "room": "叶耀珍楼407", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t58", "week": 10, "day": "周二", "period": 2, "displayName": "第10周周二(11.10) 第2大节", "room": "叶耀珍楼407", "periods": "5-6节", "cancelled": false, "originalNote": ""},
  {"id": "t59", "week": 10, "day": "周三", "period": 1, "displayName": "第10周周三(11.11) 第1大节", "room": "叶耀珍楼304", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t60", "week": 10, "day": "周三", "period": 2, "displayName": "第10周周三(11.11) 第2大节", "room": "叶耀珍楼304", "periods": "5-6节", "cancelled": false, "originalNote": ""},
  {"id": "t61", "week": 10, "day": "周四", "period": 1, "displayName": "第10周周四(11.12) 第1大节", "room": "叶耀珍楼407", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t62", "week": 10, "day": "周四", "period": 2, "displayName": "第10周周四(11.12) 第2大节", "room": "叶耀珍楼407", "periods": "5-6节", "cancelled": false, "originalNote": ""},
  {"id": "t63", "week": 10, "day": "周五", "period": 1, "displayName": "第10周周五(11.13) 第1大节", "room": "叶耀珍楼407", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t64", "week": 11, "day": "周二", "period": 1, "displayName": "第11周周二(11.17) 第1大节", "room": "叶耀珍楼407", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t65", "week": 11, "day": "周二", "period": 2, "displayName": "第11周周二(11.17) 第2大节", "room": "叶耀珍楼407", "periods": "5-6节", "cancelled": false, "originalNote": ""},
  {"id": "t66", "week": 11, "day": "周三", "period": 1, "displayName": "第11周周三(11.18) 第1大节", "room": "叶耀珍楼304", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t67", "week": 11, "day": "周三", "period": 2, "displayName": "第11周周三(11.18) 第2大节", "room": "叶耀珍楼304", "periods": "5-6节", "cancelled": false, "originalNote": ""},
  {"id": "t68", "week": 11, "day": "周四", "period": 1, "displayName": "第11周周四(11.19) 第1大节", "room": "叶耀珍楼407", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t69", "week": 11, "day": "周四", "period": 2, "displayName": "第11周周四(11.19) 第2大节", "room": "叶耀珍楼407", "periods": "5-6节", "cancelled": false, "originalNote": ""},
  {"id": "t70", "week": 11, "day": "周五", "period": 1, "displayName": "第11周周五(11.20) 第1大节", "room": "叶耀珍楼407", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t71", "week": 12, "day": "周二", "period": 1, "displayName": "第12周周二(11.24) 第1大节", "room": "叶耀珍楼407", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t72", "week": 12, "day": "周二", "period": 2, "displayName": "第12周周二(11.24) 第2大节", "room": "叶耀珍楼407", "periods": "5-6节", "cancelled": false, "originalNote": ""},
  {"id": "t73", "week": 12, "day": "周三", "period": 1, "displayName": "第12周周三(11.25) 第1大节", "room": "叶耀珍楼304", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t74", "week": 12, "day": "周三", "period": 2, "displayName": "第12周周三(11.25) 第2大节", "room": "叶耀珍楼304", "periods": "5-6节", "cancelled": false, "originalNote": ""},
  {"id": "t75", "week": 12, "day": "周四", "period": 1, "displayName": "第12周周四(11.26) 第1大节", "room": "叶耀珍楼407", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t76", "week": 12, "day": "周四", "period": 2, "displayName": "第12周周四(11.26) 第2大节", "room": "叶耀珍楼407", "periods": "5-6节", "cancelled": false, "originalNote": ""},
  {"id": "t77", "week": 12, "day": "周五", "period": 1, "displayName": "第12周周五(11.27) 第1大节", "room": "叶耀珍楼407", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t78", "week": 13, "day": "周二", "period": 1, "displayName": "第13周周二(12.1) 第1大节", "room": "叶耀珍楼407", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t79", "week": 13, "day": "周二", "period": 2, "displayName": "第13周周二(12.1) 第2大节", "room": "叶耀珍楼407", "periods": "5-6节", "cancelled": false, "originalNote": ""},
  {"id": "t80", "week": 13, "day": "周三", "period": 1, "displayName": "第13周周三(12.2) 第1大节", "room": "叶耀珍楼304", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t81", "week": 13, "day": "周三", "period": 2, "displayName": "第13周周三(12.2) 第2大节", "room": "叶耀珍楼304", "periods": "5-6节", "cancelled": false, "originalNote": ""},
  {"id": "t82", "week": 13, "day": "周四", "period": 1, "displayName": "第13周周四(12.3) 第1大节", "room": "叶耀珍楼407", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t83", "week": 13, "day": "周四", "period": 2, "displayName": "第13周周四(12.3) 第2大节", "room": "叶耀珍楼407", "periods": "5-6节", "cancelled": false, "originalNote": ""},
  {"id": "t84", "week": 13, "day": "周五", "period": 1, "displayName": "第13周周五(12.4) 第1大节", "room": "叶耀珍楼407", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t85", "week": 14, "day": "周二", "period": 1, "displayName": "第14周周二(12.8) 第1大节", "room": "叶耀珍楼407", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t86", "week": 14, "day": "周二", "period": 2, "displayName": "第14周周二(12.8) 第2大节", "room": "叶耀珍楼407", "periods": "5-6节", "cancelled": false, "originalNote": ""},
  {"id": "t87", "week": 14, "day": "周三", "period": 1, "displayName": "第14周周三(12.9) 第1大节", "room": "叶耀珍楼304", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t88", "week": 14, "day": "周四", "period": 1, "displayName": "第14周周四(12.10) 第1大节", "room": "叶耀珍楼407", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t89", "week": 14, "day": "周四", "period": 2, "displayName": "第14周周四(12.10) 第2大节", "room": "叶耀珍楼407", "periods": "5-6节", "cancelled": false, "originalNote": ""},
  {"id": "t90", "week": 14, "day": "周五", "period": 1, "displayName": "第14周周五(12.11) 第1大节", "room": "叶耀珍楼407", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t91", "week": 15, "day": "周二", "period": 1, "displayName": "第15周周二(12.15) 第1大节", "room": "叶耀珍楼407", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t92", "week": 15, "day": "周二", "period": 2, "displayName": "第15周周二(12.15) 第2大节", "room": "叶耀珍楼407", "periods": "5-6节", "cancelled": false, "originalNote": ""},
  {"id": "t93", "week": 15, "day": "周三", "period": 1, "displayName": "第15周周三(12.16) 第1大节", "room": "叶耀珍楼304", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t94", "week": 15, "day": "周四", "period": 1, "displayName": "第15周周四(12.17) 第1大节", "room": "叶耀珍楼407", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t95", "week": 15, "day": "周四", "period": 2, "displayName": "第15周周四(12.17) 第2大节", "room": "叶耀珍楼407", "periods": "5-6节", "cancelled": false, "originalNote": ""},
  {"id": "t96", "week": 15, "day": "周五", "period": 1, "displayName": "第15周周五(12.18) 第1大节", "room": "叶耀珍楼407", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t97", "week": 16, "day": "周二", "period": 1, "displayName": "第16周周二(12.22) 第1大节", "room": "叶耀珍楼407", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t98", "week": 16, "day": "周二", "period": 2, "displayName": "第16周周二(12.22) 第2大节", "room": "叶耀珍楼407", "periods": "5-6节", "cancelled": false, "originalNote": ""},
  {"id": "t99", "week": 16, "day": "周三", "period": 1, "displayName": "第16周周三(12.23) 第1大节", "room": "叶耀珍楼304", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t100", "week": 16, "day": "周四", "period": 1, "displayName": "第16周周四(12.24) 第1大节", "room": "叶耀珍楼407", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t101", "week": 16, "day": "周四", "period": 2, "displayName": "第16周周四(12.24) 第2大节", "room": "叶耀珍楼407", "periods": "5-6节", "cancelled": false, "originalNote": ""},
  {"id": "t102", "week": 16, "day": "周五", "period": 1, "displayName": "第16周周五(12.25) 第1大节", "room": "叶耀珍楼407", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t103", "week": 17, "day": "周二", "period": 1, "displayName": "第17周周二(12.29) 第1大节", "room": "叶耀珍楼407", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t104", "week": 17, "day": "周二", "period": 2, "displayName": "第17周周二(12.29) 第2大节", "room": "叶耀珍楼407", "periods": "5-6节", "cancelled": false, "originalNote": ""},
  {"id": "t105", "week": 17, "day": "周三", "period": 1, "displayName": "第17周周三(12.30) 第1大节", "room": "叶耀珍楼304", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t106", "week": 17, "day": "周四", "period": 1, "displayName": "第17周周四(12.31) 第1大节", "room": "叶耀珍楼407", "periods": "3-4节", "cancelled": false, "originalNote": ""},
  {"id": "t107", "week": 17, "day": "周四", "period": 2, "displayName": "第17周周四(12.31) 第2大节", "room": "叶耀珍楼407", "periods": "5-6节", "cancelled": false, "originalNote": ""},
  {"id": "t108", "week": 17, "day": "周五", "period": 1, "displayName": "第17周周五(1.1) 第1大节", "room": "叶耀珍楼407", "periods": "3-4节", "cancelled": true, "originalNote": ""}
];
const syllabus = [
  {"id":"u1","title":"法语课的第一天","knowledgeIds":["k1","k2","k3","k4","k5","k6","k7","k8","k9","k10","k11","k12","k13","k14","k15","k16","k17","k18"],"checkedKnowledgeIds":[],"completed":false,"completedAt":null},
  {"id":"u2","title":"我是……","knowledgeIds":["k19","k20","k21","k22","k23","k24","k25","k26","k27","k28","k29","k30","k31"],"checkedKnowledgeIds":[],"completed":false,"completedAt":null},
  {"id":"u3","title":"初次见面","knowledgeIds":["k32","k33","k34","k35","k36","k37","k38","k39","k40","k41","k42"],"checkedKnowledgeIds":[],"completed":false,"completedAt":null},
  {"id":"u4","title":"介绍与自我介绍","knowledgeIds":["k43","k44","k45","k46","k47","k48","k49","k50","k51","k52","k53","k54","k55","k56","k57","k58","k59"],"checkedKnowledgeIds":[],"completed":false,"completedAt":null},
  {"id":"u5","title":"有问题吗？","knowledgeIds":["k60","k61","k62","k63","k64","k65","k66","k67","k68","k69","k70"],"checkedKnowledgeIds":[],"completed":false,"completedAt":null},
  {"id":"u6","title":"我爱我家！","knowledgeIds":["k71","k72","k73","k74","k75","k76","k77","k78","k79","k80","k81"],"checkedKnowledgeIds":[],"completed":false,"completedAt":null},
  {"id":"u7","title":"人在旅途","knowledgeIds":["k82","k83","k84","k85","k86","k87","k88","k89","k90","k91","k92","k93","k94","k95","k96"],"checkedKnowledgeIds":[],"completed":false,"completedAt":null},
  {"id":"review_mid","title":"期中复习（S1-S7）","knowledgeIds":["k97","k98","k99","k100","k101","k102","k103","k104","k105","k106"],"checkedKnowledgeIds":[],"completed":false,"completedAt":null},
  {"id":"u8","title":"真好吃啊！","knowledgeIds":["k107","k108","k109","k110","k111","k112","k113","k114","k115","k116","k117"],"checkedKnowledgeIds":[],"completed":false,"completedAt":null},
  {"id":"u9","title":"我为\"血拼\"狂！","knowledgeIds":["k118","k119","k120","k121","k122","k123","k124","k125"],"checkedKnowledgeIds":[],"completed":false,"completedAt":null},
  {"id":"u10","title":"名人都长什么样？","knowledgeIds":["k126","k127","k128","k129","k130","k131","k132","k133","k134","k135"],"checkedKnowledgeIds":[],"completed":false,"completedAt":null},
  {"id":"u11","title":"蚁居？蜗居？豪宅？","knowledgeIds":["k136","k137","k138","k139","k140","k141","k142","k143","k144"],"checkedKnowledgeIds":[],"completed":false,"completedAt":null},
  {"id":"u12","title":"到点啦！","knowledgeIds":["k145","k146","k147","k148","k149","k150","k151","k152","k153","k154"],"checkedKnowledgeIds":[],"completed":false,"completedAt":null},
  {"id":"u13","title":"生活片段","knowledgeIds":["k155","k156","k157","k158","k159","k160"],"checkedKnowledgeIds":[],"completed":false,"completedAt":null},
  {"id":"u14","title":"生存还是毁灭？（Être ou ne pas être ?）","knowledgeIds":["k161","k162","k163","k164","k165","k166","k167"],"checkedKnowledgeIds":[],"completed":false,"completedAt":null},
  {"id":"review_final","title":"期末复习（S8-S14）","knowledgeIds":["k168","k169","k170","k171","k172","k173","k174","k175","k176","k177"],"checkedKnowledgeIds":[],"completed":false,"completedAt":null}
];
const knowledgeItems = [
  {"id":"k1","name":"课堂规则","category":"其他","practices":[]},
  {"id":"k2","name":"法语水平测试","category":"其他","practices":[]},
  {"id":"k3","name":"课程plan","category":"其他","practices":[]},
  {"id":"k4","name":"字母","category":"语音","practices":[]},
  {"id":"k5","name":"拼读概念","category":"语音","practices":[]},
  {"id":"k6","name":"音素（发音）","category":"语音","practices":[]},
  {"id":"k7","name":"元音字母","category":"语音","practices":[]},
  {"id":"k8","name":"辅音字母/组合1","category":"语音","practices":[]},
  {"id":"k9","name":"百变字母E1","category":"语音","practices":[]},
  {"id":"k10","name":"元音字母组合1","category":"语音","practices":[]},
  {"id":"k11","name":"半元音1","category":"语音","practices":[]},
  {"id":"k12","name":"鼻音1","category":"语音","practices":[]},
  {"id":"k13","name":"🎬 Totem1 Nantes单词读音","category":"语音","practices":[]},
  {"id":"k14","name":"[ER]Bonjour ! 4段对话","category":"Lecture","practices":[]},
  {"id":"k15","name":"🎬 Totem2 Bienvenue","category":"Lecture","practices":[]},
  {"id":"k16","name":"法式问候1 - 基础","category":"交际","practices":[]},
  {"id":"k17","name":"自我介绍1 - 姓名1","category":"交际","practices":[]},
  {"id":"k18","name":"课堂用语1","category":"交际","practices":[]},
  {"id":"k19","name":"[回炉]百变字母E/C/G/S/H","category":"语音","practices":[]},
  {"id":"k20","name":"[语流]连音&联诵","category":"语音","practices":[]},
  {"id":"k21","name":"动词变位意识+主谓句型","category":"语法","practices":[]},
  {"id":"k22","name":"第一组动词变位","category":"语法","practices":[]},
  {"id":"k23","name":"国籍adj.","category":"语法","practices":[]},
  {"id":"k24","name":"形容词的阴阳性","category":"语法","practices":[]},
  {"id":"k25","name":"重读人称代词1","category":"语法","practices":[]},
  {"id":"k26","name":"🎧 T10 三段对话","category":"Lecture","practices":[]},
  {"id":"k27","name":"[ER]在学院2段对话","category":"Lecture","practices":[]},
  {"id":"k28","name":"自我介绍2 - 姓名2/职业/语言","category":"交际","practices":[]},
  {"id":"k29","name":"课堂用语2","category":"交际","practices":[]},
  {"id":"k30","name":"职业1 - 基础","category":"词汇","practices":[]},
  {"id":"k31","name":"国籍1","category":"词汇","practices":[]},
  {"id":"k32","name":"[回炉]半元音","category":"语音","practices":[]},
  {"id":"k33","name":"[语流]高频联诵规则、省音","category":"语音","practices":[]},
  {"id":"k34","name":"陈述句与疑问句1","category":"语法","practices":[]},
  {"id":"k35","name":"问询他人信息","category":"语法","practices":[]},
  {"id":"k36","name":"基本否定句ne...pas(S4)","category":"语法","practices":[]},
  {"id":"k37","name":"[ER]你/您6段对话","category":"Lecture","practices":[]},
  {"id":"k38","name":"[ER]街上偶遇邻居","category":"Lecture","practices":[]},
  {"id":"k39","name":"🎬 Totem3 Moi, je suis...","category":"Lecture","practices":[]},
  {"id":"k40","name":"法式问候2 - 全面","category":"交际","practices":[]},
  {"id":"k41","name":"tu/vous的使用","category":"交际","practices":[]},
  {"id":"k42","name":"数字0-10","category":"词汇","practices":[]},
  {"id":"k43","name":"[回炉]高频组合字母","category":"语音","practices":[]},
  {"id":"k44","name":"[语流]法语节奏1 - 节奏组","category":"语音","practices":[]},
  {"id":"k45","name":"C'est句型","category":"语法","practices":[]},
  {"id":"k46","name":"名词的性数（+无生名词）","category":"语法","practices":[]},
  {"id":"k47","name":"不定冠词","category":"语法","practices":[]},
  {"id":"k48","name":"形容词的性数","category":"语法","practices":[]},
  {"id":"k49","name":"形容词的位置","category":"语法","practices":[]},
  {"id":"k50","name":"疑问句1","category":"语法","practices":[]},
  {"id":"k51","name":"[ER]自我介绍3 - Profils","category":"Lecture","practices":[]},
  {"id":"k52","name":"[ER]介绍人/事物","category":"Lecture","practices":[]},
  {"id":"k53","name":"自我介绍3 - 喜好/婚姻状况/职业","category":"交际","practices":[]},
  {"id":"k54","name":"介绍他人/事物","category":"交际","practices":[]},
  {"id":"k55","name":"提出请求或询问信息","category":"交际","practices":[]},
  {"id":"k56","name":"职业2 - 全面","category":"词汇","practices":[]},
  {"id":"k57","name":"标点符号","category":"词汇","practices":[]},
  {"id":"k58","name":"数字11-69","category":"词汇","practices":[]},
  {"id":"k59","name":"小测验1【S1-4】","category":"其他","practices":[]},
  {"id":"k60","name":"[回炉]词尾字母/组合","category":"语音","practices":[]},
  {"id":"k61","name":"[语流]法语节奏2 - 节奏重音","category":"语音","practices":[]},
  {"id":"k62","name":"定/不定冠词区分","category":"语法","practices":[]},
  {"id":"k63","name":"指示形容词 ce/cette/cet/ces","category":"语法","practices":[]},
  {"id":"k64","name":"疑问句的回答oui/si/non(S7)","category":"语法","practices":[]},
  {"id":"k65","name":"[ER]问卷调查休闲活动","category":"Lecture","practices":[]},
  {"id":"k66","name":"🎬 Totem6 Film","category":"Lecture","practices":[]},
  {"id":"k67","name":"谈论兴趣爱好与休闲活动","category":"交际","practices":[]},
  {"id":"k68","name":"体育/艺术爱好","category":"词汇","practices":[]},
  {"id":"k69","name":"表达频次","category":"词汇","practices":[]},
  {"id":"k70","name":"数字70-100","category":"词汇","practices":[]},
  {"id":"k71","name":"[回炉]鼻音&去鼻化","category":"语音","practices":[]},
  {"id":"k72","name":"[语流]法语旋律/升降调","category":"语音","practices":[]},
  {"id":"k73","name":"主有形容词","category":"语法","practices":[]},
  {"id":"k74","name":"泛指代词 on","category":"语法","practices":[]},
  {"id":"k75","name":"特殊词形的形容词beau/nouveau/vieux/fou/mou","category":"语法","practices":[]},
  {"id":"k76","name":"复数形容词前de的用法","category":"语法","practices":[]},
  {"id":"k77","name":"[ER]家庭关系访谈","category":"Lecture","practices":[]},
  {"id":"k78","name":"家庭关系（成员/氛围）","category":"交际","practices":[]},
  {"id":"k79","name":"人物性格描写1","category":"交际","practices":[]},
  {"id":"k80","name":"家人称谓","category":"词汇","practices":[]},
  {"id":"k81","name":"数字101-9999","category":"词汇","practices":[]},
  {"id":"k82","name":"[回炉]班级错误TOP5","category":"语音","practices":[]},
  {"id":"k83","name":"[语流]自测练习三部曲","category":"语音","practices":[]},
  {"id":"k84","name":"国家/城市前的介词","category":"语法","practices":[]},
  {"id":"k85","name":"冠词的缩合","category":"语法","practices":[]},
  {"id":"k86","name":"无人称句","category":"语法","practices":[]},
  {"id":"k87","name":"[ER]半夜打电话","category":"Lecture","practices":[]},
  {"id":"k88","name":"[ER]明信片","category":"Lecture","practices":[]},
  {"id":"k89","name":"🎧 T24(p.26) 自我介绍","category":"Lecture","practices":[]},
  {"id":"k90","name":"[Totem] 巴黎休闲活动","category":"Lecture","practices":[]},
  {"id":"k91","name":"询问和表达时间","category":"交际","practices":[]},
  {"id":"k92","name":"一天中的各个时间段","category":"交际","practices":[]},
  {"id":"k93","name":"介绍某地","category":"交际","practices":[]},
  {"id":"k94","name":"🎬 Totem4 Paris仅画面","category":"交际","practices":[]},
  {"id":"k95","name":"常见国家&城市","category":"词汇","practices":[]},
  {"id":"k96","name":"数字10000及以上","category":"词汇","practices":[]},
  {"id":"k97","name":"法语的九大词类","category":"语法","practices":[]},
  {"id":"k98","name":"冠词复习","category":"语法","practices":[]},
  {"id":"k99","name":"句型复习1 - 陈述句","category":"语法","practices":[]},
  {"id":"k100","name":"句型复习2 - 否定句","category":"语法","practices":[]},
  {"id":"k101","name":"句型复习3 - 疑问句","category":"语法","practices":[]},
  {"id":"k102","name":"名词表","category":"词汇","practices":[]},
  {"id":"k103","name":"动词表","category":"词汇","practices":[]},
  {"id":"k104","name":"动词变位练习","category":"词汇","practices":[]},
  {"id":"k105","name":"期中测验（1h30）","category":"其他","practices":[]},
  {"id":"k106","name":"语音测试（1h30）","category":"其他","practices":[]},
  {"id":"k107","name":"部分冠词 du/de la/de l'/des","category":"语法","practices":[]},
  {"id":"k108","name":"三类冠词的区分","category":"语法","practices":[]},
  {"id":"k109","name":"否定句中冠词的变化","category":"语法","practices":[]},
  {"id":"k110","name":"第二组动词的变位","category":"语法","practices":[]},
  {"id":"k111","name":"泛指代词rien","category":"语法","practices":[]},
  {"id":"k112","name":"[ER]Les repas chez les Dupont","category":"Lecture","practices":[]},
  {"id":"k113","name":"[ER]在中餐馆","category":"Lecture","practices":[]},
  {"id":"k114","name":"🎬 Totem5 Restaurant","category":"Lecture","practices":[]},
  {"id":"k115","name":"谈论美食","category":"交际","practices":[]},
  {"id":"k116","name":"点餐常用语","category":"交际","practices":[]},
  {"id":"k117","name":"常见食物与酒水饮料","category":"词汇","practices":[]},
  {"id":"k118","name":"限定词","category":"语法","practices":[]},
  {"id":"k119","name":"直接宾语代词 le/la/les","category":"语法","practices":[]},
  {"id":"k120","name":"[ER]Folie acheteuse","category":"Lecture","practices":[]},
  {"id":"k121","name":"🎧 T26(p.27) Petit annonce + 2 appels","category":"Lecture","practices":[]},
  {"id":"k122","name":"🎬 Totem5x2 在服装店","category":"Lecture","practices":[]},
  {"id":"k123","name":"电话用语","category":"交际","practices":[]},
  {"id":"k124","name":"购物用语","category":"交际","practices":[]},
  {"id":"k125","name":"服装与配饰","category":"词汇","practices":[]},
  {"id":"k126","name":"间接宾语代词 lui/leur","category":"语法","practices":[]},
  {"id":"k127","name":"关系代词 qui","category":"语法","practices":[]},
  {"id":"k128","name":"指示代词celui/celle/ceux/celles","category":"语法","practices":[]},
  {"id":"k129","name":"[ER]班级找人","category":"Lecture","practices":[]},
  {"id":"k130","name":"[ER]狗仔时间","category":"Lecture","practices":[]},
  {"id":"k131","name":"[ER]闺蜜八卦","category":"Lecture","practices":[]},
  {"id":"k132","name":"📖 (p.71) vos personnalités préférées","category":"Lecture","practices":[]},
  {"id":"k133","name":"人物描写","category":"交际","practices":[]},
  {"id":"k134","name":"外貌体型","category":"词汇","practices":[]},
  {"id":"k135","name":"服饰花纹","category":"词汇","practices":[]},
  {"id":"k136","name":"最近将来时/最近过去时","category":"语法","practices":[]},
  {"id":"k137","name":"关系代词que从句","category":"语法","practices":[]},
  {"id":"k138","name":"序数词","category":"语法","practices":[]},
  {"id":"k139","name":"[ER]Fille au pair","category":"Lecture","practices":[]},
  {"id":"k140","name":"[ER]小梅日记","category":"Lecture","practices":[]},
  {"id":"k141","name":"谈论住房","category":"交际","practices":[]},
  {"id":"k142","name":"表达喜好","category":"交际","practices":[]},
  {"id":"k143","name":"住所","category":"词汇","practices":[]},
  {"id":"k144","name":"小测验3","category":"其他","practices":[]},
  {"id":"k145","name":"代词式动词","category":"语法","practices":[]},
  {"id":"k146","name":"泛指形容词tout","category":"语法","practices":[]},
  {"id":"k147","name":"法语动词种类","category":"语法","practices":[]},
  {"id":"k148","name":"[ER]时刻表+对应活动","category":"Lecture","practices":[]},
  {"id":"k149","name":"[ER]年轻职场妈妈的一天","category":"Lecture","practices":[]},
  {"id":"k150","name":"日常作息与活动","category":"交际","practices":[]},
  {"id":"k151","name":"时间表达法","category":"交际","practices":[]},
  {"id":"k152","name":"🎬 Totem7 Sorbonne 配旁白练习","category":"交际","practices":[]},
  {"id":"k153","name":"法国人的时间概念（自学）","category":"Lecture","practices":[]},
  {"id":"k154","name":"日常活动","category":"词汇","practices":[]},
  {"id":"k155","name":"动词的时态（过去/现在/将来）","category":"语法","practices":[]},
  {"id":"k156","name":"以avoir为助动词的复合过去时","category":"语法","practices":[]},
  {"id":"k157","name":"[ER]去年的节日片段","category":"Lecture","practices":[]},
  {"id":"k158","name":"[ER]法国的节日（自学）","category":"Lecture","practices":[]},
  {"id":"k159","name":"传统节日","category":"交际","practices":[]},
  {"id":"k160","name":"法国的节日（自学）","category":"Lecture","practices":[]},
  {"id":"k161","name":"以être为助动词的复合过去时","category":"语法","practices":[]},
  {"id":"k162","name":"过去分词的性数配合","category":"语法","practices":[]},
  {"id":"k163","name":"时间状语depuis/il y a","category":"语法","practices":[]},
  {"id":"k164","name":"[ER]Un voyage mouvementé","category":"Lecture","practices":[]},
  {"id":"k165","name":"[ER]François Cheng","category":"Lecture","practices":[]},
  {"id":"k166","name":"[ER]Coco Chanel","category":"Lecture","practices":[]},
  {"id":"k167","name":"Biographie","category":"交际","practices":[]},
  {"id":"k168","name":"动词的用法+三大时态横向对比","category":"语法","practices":[]},
  {"id":"k169","name":"限定词专题","category":"语法","practices":[]},
  {"id":"k170","name":"代词专题","category":"语法","practices":[]},
  {"id":"k171","name":"从句专题","category":"语法","practices":[]},
  {"id":"k172","name":"问句专题","category":"语法","practices":[]},
  {"id":"k173","name":"作文主题","category":"交际","practices":[]},
  {"id":"k174","name":"名词表","category":"词汇","practices":[]},
  {"id":"k175","name":"动词表","category":"词汇","practices":[]},
  {"id":"k176","name":"动词变位练习","category":"词汇","practices":[]},
  {"id":"k177","name":"期末测试（2h）","category":"其他","practices":[]}
];
const students = [{"id":"s1","studentNo":"26114500","name":"学生1","records":[]}];
const meta = {"currentLessonId":"l1","totalLessons":98,"customTags":["语音/发音","语法/句式","听力/视听","课堂互动","作业反馈"],"coreIssueOptions":["发音不准","语法混淆","听力反应慢","词汇不足","课堂互动不足","作业完成差"],"semesterStart":"2026-09-07"};
const DEFAULT_DATA = {
  timetable: timetable,
  syllabus: syllabus,
  knowledgeItems: knowledgeItems,
  lessons: [],
  students: students,
  meta: meta
};
